=== nst-guide/schema/schemas/townwaypoint.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "townwaypoint.json",
  "type": "object",
  "additionalProperties": false,
  "title": "TownWaypoint schema",
  "required": [
    "id",
    "townId",
    "name",
    "type",
    "subtype",
    "geopoint",
    "attrs",
    "feedback"
  ],
  "properties": {
    "id": {
      "type": "integer",
      "description": "Unique identifier for town waypoint"
    },
    "townId": {
      "type": "number",
      "description": "reference to Town"
    },
    "name": {
      "type": "string",
      "description": "Common name for town waypoint"
    },
    "desc": {
      "type": "string",
      "description": "longer description of waypoint"
    },
    "type": {
      "$ref": "#/definitions/TownWaypointType"
    },
    "subtype": {
      "$ref": "#/definitions/TownWaypointSubtype"
    },
    "geopoint": {
      "$ref": "common.json#/definitions/GeoPoint"
    },
    "geometry": {
      "type": "string"
    },
    "osm": {
      "$ref": "#/definitions/TownWaypointOSM"
    },
    "attrs": {
      "$ref": "#/definitions/TownWaypointAttributes"
    },
    "feedback": {
      "$ref": "#/definitions/TownWaypointFeedback"
    }
  },
  "definitions": {
    "TownWaypointType": {
      "type": "string",
      "enum": ["food", "lodging", "finance", "store", "medical"]
    },
    "TownWaypointSubtype": {
      "oneOf": [
        {
          "$ref": "#/definitions/FoodSubtype"
        },
        {
          "$ref": "#/definitions/LodgingSubtype"
        },
        {
          "$ref": "#/definitions/FinanceSubtype"
        },
        {
          "$ref": "#/definitions/StoreSubtype"
        },
        {
          "$ref": "#/definitions/MedicalSubtype"
        }
      ]
    },
    "FoodSubtype": {
      "type": "string",
      "enum": ["fastFood", "cafe", "restaurant", "bar"]
    },
    "LodgingSubtype": {
      "type": "string",
      "enum": ["hotel", "motel", "camping", "trailAngel"]
    },
    "FinanceSubtype": {
      "type": "string",
      "enum": ["atm", "bank"]
    },
    "StoreSubtype": {
      "type": "string",
      "enum": ["outdoorsStore", "grocery"]
    },
    "MedicalSubtype": {
      "type": "string",
      "enum": ["hospital", "pharmacy"]
    },
    "TownWaypointOSM": {
      "type": "object",
      "additionalProperties": false,
      "anyOf": [
        { "required": ["nodeId"] },
        { "required": ["wayId"] },
        { "required": ["relationId"] }
      ],
      "properties": {
        "nodeId": {
          "type": "integer"
        },
        "wayId": {
          "type": "integer"
        },
        "relationId": {
          "type": "integer"
        },
        "addr:housenumber": {
          "type": "string"
        },
        "addr:street": {
          "type": "string"
        },
        "addr:city": {
          "type": "string"
        },
        "addr:state": {
          "type": "string"
        },
        "amenity": {
          "type": "string"
        },
        "tourism": {
          "type": "string"
        },
        "shop": {
          "type": "string"
        },
        "opening_hours": {
          "type": "string"
        },
        "phone": {
          "type": "string"
        },
        "website": {
          "type": "string",
          "format": "uri"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "contact_email": {
          "type": "string",
          "format": "email"
        },
        "internet_access": {
          "type": "boolean"
        },
        "internet_access_fee": {
          "type": "boolean"
        },
        "toilets_disposal": {
          "type": "string"
        },
        "drinking_water": {
          "type": "boolean"
        }
      }
    },
    "TownWaypointAttributes": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "wifi": {
          "type": "boolean"
        },
        "phone": {
          "type": "string"
        },
        "website": {
          "type": "string"
        },
        "power": {
          "type": "boolean"
        },
        "shower": {
          "type": "boolean"
        },
        "showerFee": {
          "type": "string"
        },
        "laundry": {
          "type": "boolean"
        },
        "laundryFee": {
          "type": "string"
        },
        "toilets": {
          "type": "boolean"
        },
        "toiletsFlush": {
          "type": "boolean"
        },
        "acceptsResupply": {
          "type": "boolean"
        },
        "acceptsResupplyFee": {
          "type": "string"
        },
        "acceptsResupplyProvider": {
          "$ref": "#/definitions/ResupplyProvider"
        },
        "acceptsResupplyAddress": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResupplyAddress"
          }
        },
        "sendsResupply": {
          "type": "boolean"
        },
        "sendsResupplyProvider": {
          "$ref": "#/definitions/ResupplyProvider"
        }
      }
    },
    "ResupplyProvider": {
      "type": "object",
      "properties": {
        "ups": { "type": "boolean" },
        "usps": { "type": "boolean" },
        "fedex": { "type": "boolean" }
      }
    },
    "ResupplyAddress": {
      "type": "object",
      "required": ["provider", "address"],
      "properties": {
        "provider": {
          "$ref": "#/definitions/ResupplyProvider"
        },
        "address": {
          "$ref": "common.json#/definitions/Address"
        }
      }
    },
    "TownWaypointFeedback": {
      "type": "object",
      "required": ["comments", "votes"],
      "properties": {
        "comments": {
          "type": "array",
          "items": {
            "$ref": "common.json#/definitions/Comment"
          }
        },
        "votes": {
          "type": "array",
          "items": {
            "$ref": "common.json#/definitions/FeedbackVote"
          }
        }
      }
    }
  }
}

=== nst-guide/schema/tests/townwaypoint/test2.json
{
  "id": 1,
  "townId": 1,
  "name": "SureStay Hotel by Best Western Tehachapi",
  "desc": "A solid deal, popular among thru-hikers.",
  "type": "lodging",
  "subtype": "hotel",
  "geopoint": {
    "latitude": 35.1322589,
    "longitude": -118.4550271
  },
  "osm": {
    "wayId": 82576193,
    "tourism": "motel",
    "website": "https://www.bestwestern.com/en_US/book/tehachapi/hotel-rooms/surestay-hotel-by-best-western-tehachapi/propertyCode.52024.html",
    "phone": "+1-661-822-5591",
    "addr:housenumber": "418",
    "addr:street": "West Tehachapi Boulevard",
    "addr:city": "Tehachapi",
    "addr:state": "CA",
    "internet_access": true
  },
  "attrs": {
    "wifi": true,
    "power": true,
    "shower": true
  },
  "feedback": {
    "comments": [
      {
        "userId": "abc",
        "userName": "janedoe",
        "body": "great coffee",
        "direction": "north",
        "date": "2019-11-20T20:20:39Z"
      },
      {
        "userId": "xyz",
        "userName": "johndoe",
        "body": "hated it",
        "direction": "south",
        "date": "2018-11-20T20:20:39Z"
      }
    ],
    "votes": [
      {
        "userId": "abc",
        "up": true,
        "date": "2019-11-20T20:23:39Z"
      },
      {
        "userId": "xyz",
        "up": false,
        "date": "2018-11-20T20:20:39Z"
      }
    ]
  }
}
